function cfg = defaultConfig()
%DEFAULTCONFIG Build safe-default CFD configuration for MATLAB R2022b.
% Returns a fully populated struct configuration with conservative values.

cfg = struct();

cfg.version = '1.0.0';
cfg.created_utc = char(datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z'''));

cfg.geometry = struct( ...
    'mode', 'parametric', ...
    'file_path', '', ...
    'scale', 1.0);

cfg.meshing = struct();
cfg.meshing.global_size = 0.05;
cfg.meshing.growth_rate = 1.2;
cfg.meshing.local_sizing_rules = struct( ...
    'name', {'default_local_rule'}, ...
    'target_entities', {{'all'}}, ...
    'size', {0.03}, ...
    'growth_rate', {1.15}, ...
    'enabled', {true});
cfg.meshing.boundary_layer = struct( ...
    'enabled', true, ...
    'first_layer_thickness', 1.0e-3, ...
    'growth_rate', 1.2, ...
    'num_layers', 8, ...
    'max_thickness_ratio', 0.2);

cfg.mesh_quality = struct( ...
    'max_skewness', 0.85, ...
    'min_orthogonal_quality', 0.15, ...
    'max_aspect_ratio', 150.0);

cfg.solver = struct( ...
    'time_mode', 'steady', ...
    'solver_type', 'SIMPLE');

cfg.turbulence = struct( ...
    'model', 'k_omega_sst');

cfg.boundaries = struct();
cfg.boundaries.inlet = struct( ...
    'type', 'velocity_inlet', ...
    'velocity', [1.0, 0.0], ...
    'turbulence_intensity', 0.05, ...
    'length_scale', 0.1);
cfg.boundaries.outlet = struct( ...
    'type', 'pressure_outlet', ...
    'gauge_pressure', 0.0);
cfg.boundaries.wall = struct( ...
    'type', 'no_slip', ...
    'roughness_height', 0.0, ...
    'roughness_constant', 0.5);
cfg.boundaries.symmetry = struct( ...
    'type', 'symmetry_plane');

cfg.materials = struct( ...
    'density', 1.225, ...
    'viscosity', 1.7894e-5);
end
