function model = defaultDataModel(cfg)
%DEFAULTDATAMODEL Build default run-time data model structs.

if nargin < 1 || isempty(cfg)
    cfg = cfd.config.defaultConfig();
end
cfg = cfd.config.validateConfig(cfg);

model = struct();
model.meta = struct( ...
    'schema_version', '1.0.0', ...
    'created_utc', char(datetime('now', 'TimeZone', 'UTC', 'Format', 'yyyy-MM-dd''T''HH:mm:ss''Z''')), ...
    'status', 'initialized');

model.config = cfg;

model.geometry_state = struct( ...
    'is_prepared', false, ...
    'mode', cfg.geometry.mode, ...
    'source_file', cfg.geometry.file_path, ...
    'scale', cfg.geometry.scale, ...
    'boundary_tags', {{}});

model.mesh_state = struct( ...
    'is_generated', false, ...
    'num_nodes', 0, ...
    'num_elements', 0, ...
    'nodes', zeros(0,2), ...
    'elements', zeros(0,3), ...
    'quality', struct('max_skewness', NaN, 'min_orthogonal_quality', NaN, 'max_aspect_ratio', NaN));

model.physics_state = struct( ...
    'is_initialized', false, ...
    'materials', cfg.materials, ...
    'boundaries', cfg.boundaries, ...
    'turbulence_model', cfg.turbulence.model);

model.iteration_state = struct( ...
    'iteration', 0, ...
    'time', 0.0, ...
    'residuals', struct('u', Inf, 'v', Inf, 'p', Inf, 'turbulence', Inf), ...
    'cfl', NaN, ...
    'converged', false);

model.solution_state = struct( ...
    'is_solved', false, ...
    'u', zeros(0,1), ...
    'v', zeros(0,1), ...
    'p', zeros(0,1), ...
    'turbulence_fields', struct(), ...
    'mass_imbalance', NaN);

model.run_report = struct( ...
    'warnings', {{}}, ...
    'errors', {{}}, ...
    'termination_reason', 'not_started');

model = cfd.model.validateDataModel(model);
end
