classdef TestFMUInspector < matlab.unittest.TestCase
    methods(Test)
        function testInspectParsesScalarVariables(tc)
            tmp = tempname; mkdir(tmp);
            cleanup = onCleanup(@() rmdir(tmp,'s'));

            xml = [...
                '<fmiModelDescription modelName="Demo">' ...
                '<CoSimulation/>' ...
                '<ModelVariables>' ...
                '<ScalarVariable name="u" valueReference="1" causality="input" variability="continuous">' ...
                '<Real start="0" min="-1" max="1" unit="1"/>' ...
                '</ScalarVariable>' ...
                '<ScalarVariable name="y" valueReference="2" causality="output" variability="continuous">' ...
                '<Real start="0"/>' ...
                '</ScalarVariable>' ...
                '</ModelVariables>' ...
                '</fmiModelDescription>'];

            md = fullfile(tmp,'modelDescription.xml');
            fid = fopen(md,'w'); fwrite(fid,xml); fclose(fid);
            fmuPath = fullfile(tmp,'demo.fmu');
            zip(fmuPath, md);

            logger = logging.Logger(tempdir);
            meta = fmu.FMUInspector(logger).inspect(fmuPath);
            tc.verifyEqual(numel(meta.variables),2);
            tc.verifyEqual(meta.variables(1).name,"u");
            tc.verifyEqual(meta.variables(2).name,"y");
            clear cleanup
        end
    end
end
